version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_cliente"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_cliente_simple"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_servidor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_servidor_simple"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/aleatorios"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/buffer_compartido"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/cena_filosofos"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/cifrado/app"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gradle"
    directory: "/colaborar"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/directorio_remoto_cliente"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/directorio_remoto_servidor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/enviar_fichero_cliente"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/enviar_fichero_cliente_simple"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/enviar_fichero_servidor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/enviar_fichero_servidor_simple"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/lenguaje"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/ordenar_numeros"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/validar_login/app"
    schedule:
      interval: "weekly"