version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_cliente/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_cliente_simple/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_servidor/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/adivinar_numero_servidor_simple/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/aleatorios/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/buffer_compartido/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/cena_filosofos/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/cifrado/app"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gradle"
    directory: "/colaborar/app"
    schedule:
      interval: "weekly"
